# Secrets Manager, read only by the ECS execution role when a task starts (never by the tasks'
# own roles). Generated values are written once (write-only) and never stored in the state.

locals {
  db_host = aws_db_instance.main.address
  db_tls  = "sslmode=verify-full"
}

resource "aws_secretsmanager_secret" "generated" {
  for_each                = toset(["DATABASE_URL", "ADMIN_DATABASE_URL", "APP_DB_PASSWORD", "SIGNING_KEY", "PASSWORD_PEPPER"])
  name                    = "${local.secret_prefix}/${each.key}"
  description             = "${local.prefix}: ${each.key} (generated by Terraform)"
  kms_key_id              = aws_kms_key.storage.arn
  recovery_window_in_days = 30
  tags                    = local.tags
}

resource "aws_secretsmanager_secret_version" "database_url" {
  secret_id                = aws_secretsmanager_secret.generated["DATABASE_URL"].id
  secret_string_wo         = "postgres://acct_app:${ephemeral.random_password.db_app.result}@${local.db_host}:5432/acct?${local.db_tls}"
  secret_string_wo_version = var.db_passwords_version
}

resource "aws_secretsmanager_secret_version" "app_db_password" {
  secret_id                = aws_secretsmanager_secret.generated["APP_DB_PASSWORD"].id
  secret_string_wo         = ephemeral.random_password.db_app.result
  secret_string_wo_version = var.db_passwords_version
}

resource "aws_secretsmanager_secret_version" "admin_database_url" {
  secret_id                = aws_secretsmanager_secret.generated["ADMIN_DATABASE_URL"].id
  secret_string_wo         = "postgres://acct_owner:${ephemeral.random_password.db_master.result}@${local.db_host}:5432/acct?${local.db_tls}"
  secret_string_wo_version = var.db_passwords_version
}

# 32 random characters are 32 bytes; the app wants 32 bytes in base64.
ephemeral "random_password" "signing_key" {
  length  = 32
  special = false
}

ephemeral "random_password" "pepper" {
  length  = 32
  special = false
}

resource "aws_secretsmanager_secret_version" "signing_key" {
  secret_id                = aws_secretsmanager_secret.generated["SIGNING_KEY"].id
  secret_string_wo         = base64encode(ephemeral.random_password.signing_key.result)
  secret_string_wo_version = var.signing_key_version
}

# Made once. Changing the pepper would stop every password from verifying, so it has no version
# variable; replacing it needs a plan for re-hashing (see the runbook).
resource "aws_secretsmanager_secret_version" "pepper" {
  secret_id                = aws_secretsmanager_secret.generated["PASSWORD_PEPPER"].id
  secret_string_wo         = base64encode(ephemeral.random_password.pepper.result)
  secret_string_wo_version = 1
}

# Provider credentials (Stripe, Plaid, Intuit, Anthropic, email-in): created empty; an operator
# puts each value in Secrets Manager (runbook), and the services read it at start.
resource "aws_secretsmanager_secret" "provider" {
  for_each                = toset(var.provider_secret_names)
  name                    = "${local.secret_prefix}/${each.key}"
  description             = "${local.prefix}: ${each.key} (set by an operator)"
  kms_key_id              = aws_kms_key.storage.arn
  recovery_window_in_days = 30
  tags                    = local.tags
}

locals {
  # Every task of the API image gets these (ECS `secrets`: name -> secret ARN).
  app_secrets = merge(
    {
      DATABASE_URL    = aws_secretsmanager_secret.generated["DATABASE_URL"].arn
      SIGNING_KEY     = aws_secretsmanager_secret.generated["SIGNING_KEY"].arn
      PASSWORD_PEPPER = aws_secretsmanager_secret.generated["PASSWORD_PEPPER"].arn
    },
    { for name, s in aws_secretsmanager_secret.provider : name => s.arn },
  )
  # The release step also connects as the owner and sets the app role's password.
  release_secrets = merge(local.app_secrets, {
    ADMIN_DATABASE_URL = aws_secretsmanager_secret.generated["ADMIN_DATABASE_URL"].arn
    APP_DB_PASSWORD    = aws_secretsmanager_secret.generated["APP_DB_PASSWORD"].arn
  })
}
